package application.view;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import javafx.event.ActionEvent;

import javafx.scene.control.ComboBox;

public class MainWindowController {
	@FXML
	private Button logoutButton;
	@FXML
	private TextField titleTextBox;
	@FXML
	private ComboBox SubjectComboBox;
	@FXML
	private TextField maxPunctationTextBox;
	@FXML
	private ComboBox examComboBox;
	@FXML
	private ComboBox studentComboBox;
	@FXML
	private TextField resultPunctationTextBox;
	@FXML
	private Button addExamButton;
	@FXML
	private Button saveButton;
	@FXML
	private TextField degreeTextBox;

	// Event Listener on Button[#logoutButton].onAction
	@FXML
	public void logoutButtonAction(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#addExamButton].onAction
	@FXML
	public void addExamButtonAction(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#saveButton].onAction
	@FXML
	public void saveButtonAction(ActionEvent event) {
		// TODO Autogenerated
	}
}
